package com.stevezero.aws.api.apps.goaltender.storage.items.impl;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.stevezero.aws.api.storage.items.MappedItem;

/**
 * Mapped POJO for a DynamoDb UserResource item.
 */
@DynamoDBTable(tableName="goaltender-goal")
public class GoalItem implements MappedItem {
  private String key;

  @DynamoDBHashKey(attributeName = "key")
  @DynamoDBAutoGeneratedKey
  public String getKey() {
    return this.key;
  }
  public void setKey(String key) {
    this.key = key;
  }

  // TODO: implement.
}
