package com.stevezero.aws.api.apps.goaltender.storage.items.impl;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.stevezero.aws.api.storage.items.MappedItem;

/**
 * Mapped POJO for a DynamoDb UserResource item.
 */
@DynamoDBTable(tableName="goaltender-goal")
public class GoalItem implements MappedItem {
  private String key;
  private String goalText;
  private String goalCreateDateString;
  private boolean complete;

  @DynamoDBHashKey(attributeName = "key")
  @DynamoDBAutoGeneratedKey
  public String getKey() {
    return this.key;
  }
  public void setKey(String key) {
    this.key = key;
  }

  @DynamoDBAttribute(attributeName="goalText")
  public String getGoalText() {
    return goalText;
  }
  public void setGoalText(String goalText) {
    this.goalText = goalText;
  }

  @DynamoDBAttribute(attributeName="goalCreateDateString")
  public String getGoalCreateDateString() {
    return goalCreateDateString;
  }
  public void setGoalCreateDateString(String goalCreateDateString) {
    this.goalCreateDateString = goalCreateDateString;
  }

  @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.BOOL)
  @DynamoDBAttribute(attributeName="complete")
  public boolean getComplete() {
    return complete;
  }
  public void setComplete(boolean complete) {
    this.complete = complete;
  }
}
